name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Deploy to server
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            script: |
              cd /var/www/rhodium-backend
              git pull origin main
              php artisan down
              composer install --optimize-autoloader --no-dev
              php artisan migrate
              php artisan optimize
              php artisan config:cache
              php artisan event:cache
              php artisan route:cache
              php artisan up
